# Generated by Django 3.2.1 on 2023-02-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=200)),
                ('privado', models.BooleanField(default='True')),
                ('slug', models.SlugField(max_length=150)),
            ],
            options={
                'verbose_name': 'barrio',
                'verbose_name_plural': 'barrios',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='casas/imagenes/')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('lote', models.IntegerField(blank=True, null=True)),
                ('manzana', models.IntegerField(blank=True, null=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas.barrio')),
                ('imagenes', models.ManyToManyField(to='casas.Imagen')),
            ],
            options={
                'verbose_name': 'casa',
                'verbose_name_plural': 'casas',
            },
        ),
    ]
