# Generated by Django 3.2.1 on 2023-02-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='imagenPrincipal',
            field=models.ImageField(default='casas/imagenes/terron_422.jpeg', upload_to='casas/imagenesPrincipales/'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='imagenes',
            field=models.ManyToManyField(blank=True, null=True, to='casas.Imagen'),
        ),
    ]
