# Generated by Django 3.2.1 on 2023-02-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0002_auto_20230208_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='imagenPrincipal',
        ),
        migrations.AlterField(
            model_name='casa',
            name='imagenes',
            field=models.ManyToManyField(to='casas.Imagen'),
        ),
    ]
