# Generated by Django 3.2.1 on 2023-02-09 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0004_auto_20230209_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
