# Generated by Django 3.2.1 on 2023-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0005_casa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
