# Generated by Django 3.2.1 on 2023-02-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0006_imagen_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='descripcion_corta',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barrio',
            name='descripcion_larga',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagen',
            name='opcion',
            field=models.CharField(choices=[('principal', 'principal'), ('exteriores', 'exteriores'), ('interiores', 'interiores'), ('amenities', 'amenities'), ('planos', 'planos')], default='exteriores', max_length=15),
        ),
        migrations.AlterField(
            model_name='casa',
            name='descripcion_corta',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='casa',
            name='descripcion_larga',
            field=models.TextField(max_length=2000),
        ),
    ]
