# Generated by Django 3.2.1 on 2023-02-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0007_auto_20230210_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='descripcion_corta',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='descripcion_larga',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='casa',
            name='descripcion_corta',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='casa',
            name='descripcion_larga',
            field=models.TextField(max_length=1000),
        ),
    ]
