# Generated by Django 3.2.1 on 2023-02-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0008_auto_20230210_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='descripcion_corta',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='casa',
            name='descripcion_corta',
            field=models.TextField(max_length=200),
        ),
    ]
