# Generated by Django 3.2.1 on 2023-02-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0010_auto_20230210_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='descripcion_corta',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='descripcion_larga',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='casa',
            name='descripcion_corta',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='casa',
            name='descripcion_larga',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='casa',
            name='nombre',
            field=models.CharField(max_length=800),
        ),
    ]
