# Generated by Django 3.2.1 on 2023-02-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0012_auto_20230210_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='opcion',
            field=models.CharField(choices=[('principal', 'principal'), ('avance_de_obra', 'avance_de_obra'), ('exteriores', 'exteriores'), ('interiores', 'interiores'), ('planos', 'planos')], default='exteriores', max_length=15),
        ),
    ]
