# Generated by Django 5.0.7 on 2024-07-13 19:48

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0013_alter_imagen_opcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrio',
            old_name='descripcion_larga',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='barrio',
            name='descripcion_corta',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='descripcion_corta',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='descripcion_larga',
        ),
        migrations.AddField(
            model_name='barrio',
            name='imagen',
            field=models.ImageField(default=1, upload_to='barrios/imagenes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barrio',
            name='titulo',
            field=models.TextField(default='TITULOOOOO', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='altura',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='calle',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='codigo_postal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='informacion',
            field=jsonfield.fields.JSONField(default={'INFO1': 'Esta es la información del tip1'}, verbose_name='Información adicional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='precio_dols',
            field=models.PositiveIntegerField(default=350000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casa',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='casa',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
