# Generated by Django 5.0.7 on 2024-07-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0014_rename_descripcion_larga_barrio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='descripcion',
            field=models.TextField(max_length=450),
        ),
    ]
