# Generated by Django 5.0.7 on 2024-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0015_alter_barrio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
