# Generated by Django 5.0.7 on 2024-07-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0016_alter_barrio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='slug',
            field=models.SlugField(max_length=70),
        ),
        migrations.AlterField(
            model_name='casa',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='slug',
            field=models.SlugField(),
        ),
    ]
