# Generated by Django 5.0.7 on 2024-07-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0019_alter_barrio_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='precio_dols',
        ),
        migrations.AddField(
            model_name='casa',
            name='ambientes',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='baños',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='dormitorios',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='precio',
            field=models.PositiveIntegerField(default=450000, verbose_name='Precio en dolares de la casa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='sup_cubierta',
            field=models.PositiveIntegerField(default=230, verbose_name='Superficie cubierta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='sup_terreno',
            field=models.PositiveIntegerField(default=300, verbose_name='Superficie del terreno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='video',
            field=models.FileField(default=3, upload_to='casas/videos/'),
            preserve_default=False,
        ),
    ]
