# Generated by Django 5.0.7 on 2024-07-16 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0020_remove_casa_precio_dols_casa_ambientes_casa_baños_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Tipo de operación',
                'verbose_name_plural': 'Tipos de operaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Tipo de propiedad',
                'verbose_name_plural': 'Tipos de propiedades',
            },
        ),
        migrations.AddField(
            model_name='casa',
            name='tipo_operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casas.tipooperacion'),
        ),
        migrations.AddField(
            model_name='casa',
            name='tipo_propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casas.tipopropiedad'),
        ),
    ]
