# Generated by Django 5.0.7 on 2024-07-16 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0021_tipooperacion_tipopropiedad_casa_tipo_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='tipo_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas.tipooperacion'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas.tipopropiedad'),
        ),
    ]
