# Generated by Django 5.0.7 on 2024-07-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0022_alter_casa_tipo_operacion_alter_casa_tipo_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='descripcion',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Id temporibus modi optio. Modi eum perferendis qui alias, iure ipsa iusto doloremque delectus quod eius odio, quo minus deleniti omnis maxime dolorem quaerat, similique aspernatur mollitia commodi? Ex enim minima nam voluptatem! Quaerat, nisi eos. Quia at illum eos natus repudiandae beatae harum asperiores ipsum sunt. Sapiente at dicta autem dignissimos libero alias in dolorem optio eos molestiae, eius explicabo fuga hic ducimus aut provident similique saepe quod eum! Dignissimos aliquam tempora molestiae? Animi deleniti adipisci sed amet quasi. Minima unde blanditiis in delectus! Exercitationem sed rerum accusantium illum aliquam aut eius vero consequuntur officiis ex velit itaque a necessitatibus quas obcaecati, ipsum laudantium corrupti! Minima eaque maiores modi explicabo adipisci!', max_length=120, verbose_name='Descripción acotada de la casa'),
            preserve_default=False,
        ),
    ]
