# Generated by Django 5.0.7 on 2024-07-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0023_casa_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='imagen_principal',
            field=models.ImageField(default=1, upload_to='casas/imagenes/principales', verbose_name='Imágen principal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagen',
            name='opcion',
            field=models.CharField(choices=[('avance_de_obra', 'avance_de_obra'), ('exteriores', 'exteriores'), ('interiores', 'interiores'), ('planos', 'planos')], default='exteriores', max_length=15),
        ),
    ]
