# Generated by Django 5.0.7 on 2024-07-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0024_casa_imagen_principal_alter_imagen_opcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='imagen_principal1',
            field=models.ImageField(default=1, upload_to='casas/imagenes/secundaria', verbose_name='Imágen principal con dimensiones (1350 x 550)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casa',
            name='imagen_principal',
            field=models.ImageField(upload_to='casas/imagenes/principales', verbose_name='Imágen principal con dimensiones (320 x 300)'),
        ),
    ]
