# Generated by Django 5.0.7 on 2024-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0026_casa_imagen_principal2_alter_casa_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='imagen_principal',
            field=models.ImageField(upload_to='casas/imagenes/principales', verbose_name='Imágen principal con dimensiones 4x3 (ancho x alto)'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='imagen_principal1',
            field=models.ImageField(upload_to='casas/imagenes/secundaria', verbose_name='Imágen principal con dimensiones 16x9 (ancho x alto)'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='imagen_principal2',
            field=models.ImageField(upload_to='casas/imagenes/terciaria', verbose_name='Imágen principal con dimensiones 3x4 (ancho x alto)'),
        ),
    ]
