# Generated by Django 5.0.7 on 2024-08-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0027_alter_casa_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='video',
            field=models.CharField(max_length=100, verbose_name='Url del video de youtube de la casa'),
        ),
    ]
