# Generated by Django 5.0.7 on 2024-08-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0028_alter_casa_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='opcion',
            field=models.CharField(choices=[('exteriores', 'exteriores'), ('interiores', 'interiores'), ('planos', 'planos')], default='exteriores', max_length=15),
        ),
    ]
