# Generated by Django 5.0.7 on 2024-07-13 20:33

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre de la inmobiliaria')),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descrpción breve de la inmobiliaria')),
                ('numero', models.PositiveIntegerField(verbose_name='Numero de telefono para contactarse con la inmobiliaria')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email para contactarse con la inmobiliaria')),
                ('ig', models.CharField(max_length=30, verbose_name='Instagram de la inmobiliaria')),
                ('medio_contacto', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Medio de contacto extra')),
                ('titulo', models.TextField(max_length=140, verbose_name='Titulo de texto de la pagina nosotros')),
                ('texto', models.TextField(max_length=500, verbose_name='Texto de la pagina nosotros')),
                ('imagen1', models.ImageField(upload_to='nosotros/seccion2/imagenes', verbose_name='Imágen del texto ubicado a la izquierda de la segunda sección de la página nosotros')),
                ('subtitulo1', models.CharField(max_length=40, verbose_name='Subtitulo del texto ubicado a la izquierda de la segunda sección de la página nosotros')),
                ('titulo1', models.CharField(max_length=30, verbose_name='Título del texto ubicado a la izquierda de la segunda sección de la página nosotros')),
                ('texto1', models.CharField(max_length=250, verbose_name='Texto ubicado a la izquierda de la segunda sección de la página nosotros')),
                ('imagen2', models.ImageField(upload_to='nosotros/seccion2/imagenes', verbose_name='Imágen del texto ubicado a la derecha de la segunda sección de la página nosotros')),
                ('subtitulo2', models.CharField(max_length=40, verbose_name='Subtitulo del texto ubicado a la derecha de la segunda sección de la página nosotros')),
                ('titulo2', models.CharField(max_length=30, verbose_name='Título del texto ubicado a la derecha de la segunda sección de la página nosotros')),
                ('texto2', models.CharField(max_length=250, verbose_name='Texto ubicado a la derecha de la segunda sección de la página nosotros')),
            ],
            options={
                'verbose_name': 'Información general',
            },
        ),
    ]
