# Generated by Django 5.0.7 on 2024-07-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_informacion_options_informacion_gris_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacion',
            name='id',
        ),
        migrations.AddField(
            model_name='informacion',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
