# Generated by Django 5.0.7 on 2024-07-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_informacion_id_informacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='titulo_casas_home',
            field=models.CharField(default='NUESTRAS CASAS', max_length=20, verbose_name='Titulo que aparece arriba de las casas del home'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacion',
            name='gris',
            field=models.CharField(max_length=30, verbose_name='Titulo en gris de la página de home'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='negrito',
            field=models.CharField(max_length=20, verbose_name='Titulo en negrito de la página de home'),
        ),
    ]
