# Generated by Django 5.0.7 on 2024-07-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_informacion_titulo_casas_home_alter_informacion_gris_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='texto_dos_contacto',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas quis eaque tenetur hic voluptas sapiente', max_length=100, verbose_name='Texto del segundo paso de contacto del home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacion',
            name='texto_tres_contacto',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas quis eaque tenetur hic voluptas sapiente', max_length=100, verbose_name='Texto del tercer paso de contacto del home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacion',
            name='texto_uno_contacto',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas quis', max_length=100, verbose_name='Texto del primer paso de contacto del home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacion',
            name='titulo_contacto_home',
            field=models.CharField(default='¿Cómo contactarnos?', max_length=24, verbose_name='Titulo de los pasos de contacto del home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacion',
            name='titulo_dos_contacto',
            field=models.CharField(default='Coordinamos reunión', max_length=28, verbose_name='Titulo del segundo paso de contacto del home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacion',
            name='titulo_tres_contacto',
            field=models.CharField(default='Último paso', max_length=28, verbose_name='Titulo del tercer paso de contacto del home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacion',
            name='titulo_uno_contacto',
            field=models.CharField(default='Realizá tu consulta', max_length=28, verbose_name='Titulo del primer paso de contacto del home'),
            preserve_default=False,
        ),
    ]
