# Generated by Django 5.0.7 on 2024-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_informacion_texto_dos_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='ultimo_texto_contacto',
            field=models.TextField(default='Realiza los pasos tocando en el botón de abajo', max_length=120, verbose_name='Texto de la última caja de pasos de contactos del home'),
            preserve_default=False,
        ),
    ]
