# Generated by Django 5.0.7 on 2024-07-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_informacion_ultimo_texto_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='texto_dos_contacto',
            field=models.TextField(max_length=110, verbose_name='Texto del segundo paso de contacto del home'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='texto_tres_contacto',
            field=models.TextField(max_length=110, verbose_name='Texto del tercer paso de contacto del home'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='texto_uno_contacto',
            field=models.TextField(max_length=110, verbose_name='Texto del primer paso de contacto del home'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='ultimo_texto_contacto',
            field=models.TextField(max_length=110, verbose_name='Texto de la última caja de pasos de contactos del home'),
        ),
    ]
