# Generated by Django 5.0.7 on 2024-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_informacion_texto_dos_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descrpción breve de la inmobiliaria'),
        ),
    ]
