# Generated by Django 5.0.7 on 2024-07-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_informacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='subtitulo',
            field=models.CharField(default='¿QUIENES SOMOS?', max_length=50, verbose_name='Subtítulo del texto de la página nosotros'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacion',
            name='titulo',
            field=models.TextField(max_length=140, verbose_name='Título del texto de la pagina nosotros'),
        ),
    ]
