# Generated by Django 5.0.7 on 2024-07-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_informacion_subtitulo_alter_informacion_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacion',
            old_name='imagen1',
            new_name='imagen1_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='imagen2',
            new_name='imagen2_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='subtitulo1',
            new_name='subtitulo1_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='subtitulo2',
            new_name='subtitulo2_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='subtitulo',
            new_name='subtitulo_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='texto1',
            new_name='texto1_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='texto2',
            new_name='texto2_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='texto',
            new_name='texto_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='titulo1',
            new_name='titulo1_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='titulo2',
            new_name='titulo2_nosotros',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='titulo',
            new_name='titulo_nosotros',
        ),
    ]
