# Generated by Django 5.0.7 on 2024-07-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_informacion_subtitulo1_nosotros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='texto1_nosotros',
            field=models.TextField(max_length=160, verbose_name='Texto ubicado a la izquierda de la segunda sección de la página nosotros'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='texto2_nosotros',
            field=models.TextField(max_length=160, verbose_name='Texto ubicado a la derecha de la segunda sección de la página nosotros'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='texto_nosotros',
            field=models.TextField(max_length=450, verbose_name='Texto de la pagina nosotros'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='titulo_nosotros',
            field=models.TextField(max_length=100, verbose_name='Título del texto de la pagina nosotros'),
        ),
    ]
