# Generated by Django 5.0.7 on 2024-07-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_informacion_texto1_nosotros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='subtitulo1_nosotros',
            field=models.CharField(max_length=22, verbose_name='Subtitulo del texto ubicado a la izquierda de la segunda sección de la página nosotros'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='subtitulo2_nosotros',
            field=models.CharField(max_length=22, verbose_name='Subtitulo del texto ubicado a la derecha de la segunda sección de la página nosotros'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='titulo1_nosotros',
            field=models.TextField(max_length=16, verbose_name='Título del texto ubicado a la izquierda de la segunda sección de la página nosotros'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='titulo2_nosotros',
            field=models.TextField(max_length=16, verbose_name='Título del texto ubicado a la derecha de la segunda sección de la página nosotros'),
        ),
    ]
