# Generated by Django 5.0.7 on 2024-08-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_informacion_subtitulo1_nosotros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_arrow', models.ImageField(upload_to='general/arrow/')),
                ('right_arrow', models.ImageField(upload_to='general/arrow/')),
            ],
        ),
    ]
