# Generated by Django 5.0.7 on 2024-08-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='close_complete',
            field=models.ImageField(default=1, upload_to='general/complete/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='open_complete',
            field=models.ImageField(default=1, upload_to='general/complete/'),
            preserve_default=False,
        ),
    ]
